#!/bin/bash
set -euo pipefail

CONTEXT=$(echo "${NP_ACTION_CONTEXT:-$CONTEXT}" | sed "s/^'//;s/'$//" | jq -c '.notification // .')

SERVICE_ID=$(echo "$CONTEXT" | jq -r '.service.id')
export SERVICE_ID
export SCOPE_ID=""
